spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#minio配置
  minio:
    access-key: admin
    secret-key: admin123
    url: http://172.28.50.144:9090
    bucket-name: test
  thymeleaf:
    cache: false
server:
  port: 8081